export const DATABASE_NAME = 'nav_instructor_db';
export const CORDOVA_SQLITE = 'cordova-sqlite';
export const DOCUMENT_KEYS = {
  CLASSES: 'classes',
  CLASSES_COMPETENCY_STATS: 'classes_competency_stats',
  CLASSES_COURSES: 'classes_courses',
  CLASSES_DCA_PERFORMANCE: 'classes_dca_performance',
  CLASSES_PERFORMANCE: 'classes_performance',
  CLASS_COMPETENCY_REPORT: 'class_{classId}_competency_report',
  CLASS_COURSE: 'class_course_{courseId}',
  CLASS_COURSE_MAP_CONTENT: 'class_{classId}_course_map_content',
  CLASS_DCA_CONTENTS: 'class_{classId}_activities',
  CLASS_DCA_CONTENT_PERFORMANCE: 'class_{classId}_activities_{contentType}_performance',
  CLASS_DCA_PERFORMANCE: 'class_{classId}_dca_performance',
  CLASS_DCA_USERS: 'class_{classId}_dca_{contentId}_users',
  CLASS_MEMBERS: 'class_{classId}_members',
  CLASS_SECONDARY_CLASSES_DETAILS: 'class_{classId}_secondary_classes',
  COLLECTION: 'collection_{collectionId}',
  COLLECTION_MEDIA: 'collection_{collectionId}_media',
  LAST_UPLOAD_ID: 'last_upload_id',
  MILESTONES: 'course_{courseId}_fw_{fwCode}_milestones',
  STUDENT_MILESTONES: 'course_{courseId}_fw_{fwCode}_student_{userId}_milestones',
  MILESTONE_LESSONS: 'course_{course_id}_milestone_{milestoneId}_lessons',
  MILESTONE_LESSON_PERFORMANCE: 'class_{classId}_course_{courseId}_fw_{fwCode}_milestone_{milestoneId}_performace',
  MILESTONE_PERFORMANCE: 'class_{classId}_course_{courseId}_fw_{fwCode}_milestone_performace',
  STUDENT_MILESTONE_PERFORMANCE: 'class_{classId}_course_{courseId}_fw_{fwCode}_student_{studentId}_milestone_performace',
  OFFLINE_CLASSES_SETTINGS: 'offline_classes_settings',
  OFFLINE_DATA_EVENTS: 'offline_data_events',
  PROFILE_PREFERENCE: 'profile_preference',
  STUDENT_CURRENT_LOCATION: 'class_{classId}_course_{courseId}_fw_{fwCode}_user_{userId}_student_current_location',
  STUDENT_UNITS_PERFORMANCE: 'class_{classId}_course_{courseId}_student_{studentId}_units_performance',
  TAXONOMY_CLASSIFICATIONS: 'taxonomy_classifications',
  TAXONOMY_CROSS_WALK_FWC: 'taxonomy_{subjectCode}_cross_walk_fwc',
  TAXONOMY_GRADES_BY_SUBJECT: 'taxonomy_{subjectCode}_grades_by_subject',
  TAXONOMY_GRADE_BOUNDARY_BY_SUBJECT: 'taxonomy_{subjectCode}_grade_boundary_by_subject',
  TAXONOMY_PROFICIENCY_STUDENT_SUBJECT: 'taxonomy_{subjectCode}_proficiency_student_subject',
  TAXONOMY_SUBJECT_DOMAIN_TOPIC_META_DATA: 'taxonomy_{subjectId}_subject_domain_topic_meta_data',
  TAXONOMY_USER_COMPETENCY_MATRIX: 'taxonomy_{subjectId}_user_{userId}_competency_matrix',
  TENANT_SETTINGS: 'tenant_settings',
  UNIT0_LIST: 'class_{classId}_course_{courseId}_unit0_list',
  UNITS_PERFORMANCE: 'class_{classId}_course_{courseId}_units_performance'
};