export const environment = {
  production: false,
  APP_VERSION: '2.8.4',
  API_END_POINT: 'https://prodb.gooru.org',
  APP_ID: 'NavigatorInstructor',
  TRANSLATION_APP_ID: 'bdc8be5b-f6bd-482f-af44-cc73cc676e57',
  PARSE_API_PATH: 'instructor/parse',
  CLIENT_ID: 'ba956a97-ae15-11e5-a302-f8a963065976',
  CLIENT_KEY: 'c2hlZWJhbkBnb29ydWxlYXJuaW5nLm9yZw==',
  GOORU_TENANT_ID: 'ba956a97-ae15-11e5-a302-f8a963065976',
  CDN_URL: 'https://cdn.gooru.org',
  TENANT_URL: 'https://tl-b.gooru.org/',
  TENANT_DOMAIN_NAME: 'tl-b.gooru.org',
  SHOW_PUBLIC_CLASS: true,
  YOUTUBE_IFRAME_API: 'https://www.youtube.com/iframe_api',
  SHOW_SECONDARY_CLASS: true,
  ZOOM_PASSWORD: '1234567890',
  TENANT_SIGNUP_URL: 'https://prodb.gooru.org/',
  SEND_SIGNUP_MAIL_INVITE: true,
  IS_ONLINE: true,
  PACKAGE_NAME: 'org.gooru.navigator.instructor',
  S3_BUCKET_URL: 'https://offlinecontentcdn.gooru.org',
};
